### ISSUE TITLE
코드 참고 중 질문사항

### ISSUE THREAD

**Issue by dev32user** [gunkim/springboot-security-jwt#1]
https://github.com/gunkim/spring-security-jwt-sample/blob/557aceb30c57fc005ac8c0d1051da9cac1d001be/src/main/java/io/github/gunkim/security/provider/JwtAuthenticationProvider.java#L28

위 구문에서 return 다음 부분을 괄호로 감싸는 이유는 무엇인가요? 
```java
return JwtAuthenticationToken.class.isAssignableFrom(authentication);
```
위 코드와 같은 꼴로 작성해도 정상작동하는 것을 확인했습니다. 
JwtTokenIssueProvider.supports() 메서드의 return 부분에서도 똑같이 괄호로 감싸놓은 것을 확인하여 궁금합니다.

**Comment by dev32user** [comment]
관련해서 찾아보던 중 return 형식에 대한 Oracle의 컨벤션 문서를 확인했습니다. 
https://www.oracle.com/java/technologies/javase/codeconventions-statements.html#438
아래는 해당 문서 7.3에서 발췌한 내용입니다. 

```
7.3 return Statements
A return statement with a value should not use parentheses unless they make the return value
more obvious in some way. Example:
```
```java 
return;
return myDisk.size();
return (size ? size : defaultSize);
```

본 이슈에 적힌 내용(JwtAuthenticationProvider.java의 28번 줄)은 순전히 코드 작성 스타일의 취향에 기인한 것인가요?

**Comment by gunkim** [comment]
말씀하신 것처럼 괄호를 제거해도 문제가 없습니다. 단순히 코드 스타일의 취향에 기인한 것이라고 이해하시면 될 것 같아요.
사실 저도 괄호가 없는 부분이 취향인데 의도와 다르게 IDE 레벨에서 저도 모르게 reformat돼서 올라갔던 코드로 보이네요.

**Comment by dev32user** [comment]
의문점이 해결됐습니다. 친절한 답변 감사합니다.
